[phases.setup]
nixPkgs = ['nodejs_24', 'pnpm']

[phases.build]
cmds = [
  'corepack enable && corepack prepare pnpm@9.15.5 --activate',
  'pnpm install --frozen-lockfile=false',
  'cd settle-api && pnpm run build'
]

[start]
cmd = 'cd settle-api && node dist/main.js'
